### ISSUE TITLE
Algolia: Response not successful: Received status code 429

### ISSUE THREAD

**Issue by bauhem** [u12206050/gridsome-plugin-algolia#13]
Hello, I have a problem with rate limitations and Algolia. Netlify gives me the following error: Algolia: Response not successful: Received status code 429. Do you have any tips on how we can avoid this using your plugins in Gridsome?

Thanks

**Comment by u12206050** [comment]
Hei, What does your config look like?
Do you have unique id for each item you index and a data changed that you can use to check what items have changed?

**Comment by bauhem** [comment]
<img width="509" alt="Capture d’écran, le 2022-03-29 à 09 11 30" src="https://user-images.githubusercontent.com/5316552/160618918-a25949b5-9a23-4ef8-b7c6-90e25ac1aa35.png">
<img width="714" alt="Capture d’écran, le 2022-03-29 à 09 11 20" src="https://user-images.githubusercontent.com/5316552/160618923-a78149eb-3708-41c5-8498-daf7352c5a6e.png">

**Comment by bauhem** [comment]
Is that related to this, because my index would have more than 1000 items.

<img width="577" alt="Capture d’écran, le 2022-03-29 à 09 12 50" src="https://user-images.githubusercontent.com/5316552/160619188-bcc5c8ad-7a15-4939-b8ce-bfdb8c3bfc18.png">
?

**Comment by bauhem** [comment]
And the Netlify (or Vercel) error

<img width="999" alt="Capture d’écran, le 2022-03-29 à 09 14 10" src="https://user-images.githubusercontent.com/5316552/160619418-a58b2b2d-40df-4f0f-ab62-16f796addab6.png">

**Comment by bauhem** [comment]
I was wondering if your plugins could throttle or send in batch or any other solution.

https://support.algolia.com/hc/en-us/articles/4406975251089-Is-there-a-rate-limit-/#what-happens-when-the-rate-limit-is-reached

**Comment by u12206050** [comment]
How many items do you have?
It might be that if you have never indexed to Algolia before, that to just get it running try running the build process a few times so indexing can happen, and after a while only the changes should start triggering.

However, if you have an insane amount of documents typically 100000+ then it could also be that the partial update is the issue when it is trying to fetch a diff.

**Comment by u12206050** [comment]
> And the Netlify (or Vercel) error
> 
> <img alt="Capture d’écran, le 2022-03-29 à 09 14 10" width="999" src="https://user-images.githubusercontent.com/5316552/160619418-a58b2b2d-40df-4f0f-ab62-16f796addab6.png">

Do you get the same output every time you run a build.

Meaning does it always show `items in collection 0`
 If so then there is a a clear issue with loading the diff. Are you able to verify that you do indeed have items in your index (within algolia dashboard)?

**Comment by u12206050** [comment]
Nevermind all that.

Just realised the error is being thrown here
```
      const result = await graphql(query);
      if (result.errors) {
        throw new Error(`failed to index to Algolia: ${result.errors}`);
      }
```
Meaning while trying to execute your graphql query, so might be your server that is rate limiting.

Also the fact that in your log output it says `items in collection 0` means that there is nothing returned from your transformer either.

Add a console log within your transformer to check it is being called with the data you expect.

**Comment by bauhem** [comment]
Ok, i'll follow your advice about get it running, and running again until only the updated one are sent. Thanks for your time.

**Comment by u12206050** [comment]
Do you mind sharing your config.
How often are you building, and do you use an id for the items you index so
you don't have to reindex if nothing has changed?
